### ISSUE TITLE
How to tilt the view

### ISSUE THREAD

**Issue by KarlZeilhofer** [alexandrevicenzi/SnakeGL#1]
Hi, 

nice game, which compiles without any problems here on a Linux Mint 19. 
Are there any controls to tilt the view?

Greets, 
Karl

**Comment by alexandrevicenzi** [comment]
Hi, controls are in readme file, space bar changes view/camera angle.

**Comment by KarlZeilhofer** [comment]
Sorry, for overlooking that! Thanks for your answer!
